### PR TITLE
WotLK Update

### PR DESCRIPTION
**Pull request by Nakroma**
Updated:
- [x] Professions
- [x] Wowhead
- [x] Blizzard API

### CODE REVIEW

**Comment by Nakroma** [comment]
I believe the Wowhead scraping to be mostly adjusted now, at least the items so now it will be mainly waiting for the WotLK Blizzard API to come up

**Comment by Andrioden** [comment]
@Nakroma - Will the `data/json/zones.json` be updated later? I see you updated the scraping code but not the datafile itself. Humbly asking, thanks a lot for the data for classic and tbc classic!

**Comment by Nakroma** [comment]
> @Nakroma - Will the `data/json/zones.json` be updated later? I see you updated the scraping code but not the datafile itself. Humbly asking, thanks a lot for the data for classic and tbc classic!

Hey, yeah I'll update the data as soon as all the scraping code is ready.

**Comment by albri** [comment]
Hey @Nakroma, I believe the Blizzard API is now working for WoTLK following prepatch. The namespace `static-classic-us` returns WoTLK items now (using the namespace `static-3.4.0_45264-classic-us` under the hood).

image

**Comment by Nakroma** [comment]
```
    Change: 503 items missing.
    Change: 13700 items added.
    Change: 19684 items changed.
 ```
 Looks good to me, did a few spot checks and it looks fine. Gonna go ahead and merge and release. Lemme know if anythings wrong!

**Pull request merged**
